// Generated by CommonJS Everywhere 0.9.4
(function (global) {
  function require(file, parentModule) {
    if ({}.hasOwnProperty.call(require.cache, file))
      return require.cache[file];
    var resolved = require.resolve(file);
    if (!resolved)
      throw new Error('Failed to resolve module ' + file);
    var module$ = {
        id: file,
        require: require,
        filename: file,
        exports: {},
        loaded: false,
        parent: parentModule,
        children: []
      };
    if (parentModule)
      parentModule.children.push(module$);
    var dirname = file.slice(0, file.lastIndexOf('/') + 1);
    require.cache[file] = module$.exports;
    resolved.call(module$.exports, module$, module$.exports, dirname, file);
    module$.loaded = true;
    return require.cache[file] = module$.exports;
  }
  require.modules = {};
  require.cache = {};
  require.resolve = function (file) {
    return {}.hasOwnProperty.call(require.modules, file) ? require.modules[file] : void 0;
  };
  require.define = function (file, fn) {
    require.modules[file] = fn;
  };
  require.define('/options.js', function (module, exports, __dirname, __filename) {
    var Options = require('/../../node_modules/fantasy-options/option.js', module);
    exports = module.exports = Options;
  });
  require.define('/../../node_modules/fantasy-options/option.js', function (module, exports, __dirname, __filename) {
    var daggy = require('/../../node_modules/fantasy-options/node_modules/daggy/daggy.js', module), Option = daggy.taggedSum({
        Some: ['x'],
        None: []
      });
    Option.prototype.fold = function (f, g) {
      return this.cata({
        Some: f,
        None: g
      });
    };
    Option.of = Option.Some;
    Option.prototype.orElse = function (x) {
      return this.fold(function (x) {
        return Option.Some(x);
      }, function () {
        return x;
      });
    };
    Option.prototype.getOrElse = function (x) {
      return this.fold(function (a) {
        return a;
      }, function () {
        return x;
      });
    };
    Option.prototype.chain = function (f) {
      return this.fold(function (a) {
        return f(a);
      }, function () {
        return Option.None;
      });
    };
    Option.prototype.concat = function (x) {
      return this.fold(function (a) {
        return x.chain(function (b) {
          return Option.Some(a.concat(b));
        });
      }, function () {
        return b;
      });
    };
    Option.prototype.map = function (f) {
      return this.chain(function (a) {
        return Option.of(f(a));
      });
    };
    Option.prototype.ap = function (a) {
      return this.chain(function (f) {
        return a.map(f);
      });
    };
    if (typeof module != 'undefined')
      module.exports = Option;
  });
  require.define('/../../node_modules/fantasy-options/node_modules/daggy/daggy.js', function (module, exports, __dirname, __filename) {
    (function (global, factory) {
      'use strict';
      if (typeof define === 'function' && define.amd) {
        define(['exports'], factory);
      } else if (typeof exports !== 'undefined') {
        factory(exports);
      } else {
        global.daggy = {};
        factory(global.daggy);
      }
    }(this, function (exports) {
      function create(proto) {
        function Ctor() {
        }
        Ctor.prototype = proto;
        return new Ctor;
      }
      exports.create = create;
      function getInstance(self, constructor) {
        return self instanceof constructor ? self : create(constructor.prototype);
      }
      exports.getInstance = getInstance;
      function tagged() {
        var fields = [].slice.apply(arguments);
        function wrapped() {
          var self = getInstance(this, wrapped), i;
          if (arguments.length != fields.length)
            throw new TypeError('Expected ' + fields.length + ' arguments, got ' + arguments.length);
          for (i = 0; i < fields.length; i++)
            self[fields[i]] = arguments[i];
          return self;
        }
        wrapped._length = fields.length;
        return wrapped;
      }
      exports.tagged = tagged;
      function taggedSum(constructors) {
        var key;
        function definitions() {
          throw new TypeError('Tagged sum was called instead of one of its properties.');
        }
        function makeCata(key) {
          return function (dispatches) {
            var fields = constructors[key], args = [], i;
            if (!dispatches[key])
              throw new TypeError("Constructors given to cata didn't include: " + key);
            for (i = 0; i < fields.length; i++)
              args.push(this[fields[i]]);
            return dispatches[key].apply(this, args);
          };
        }
        function makeProto(key) {
          var proto = create(definitions.prototype);
          proto.cata = makeCata(key);
          return proto;
        }
        for (key in constructors) {
          if (!constructors[key].length) {
            definitions[key] = makeProto(key);
            continue;
          }
          definitions[key] = tagged.apply(null, constructors[key]);
          definitions[key].prototype = makeProto(key);
        }
        return definitions;
      }
      exports.taggedSum = taggedSum;
    }));
  });
  global.Options = require('/options.js');
}.call(this, this));
